### ISSUE TITLE
How do you trigger routes from markup?

### ISSUE THREAD

**Issue by mgutz** [ayamflow/vue-route#15]
In template

~~~html
<li><a href="#!/login">Log In</a></li>
~~~

In the root VM

~~~js
    routes: {
        '/home': {
            componentId: "home",
            isDefault: true
        },

        '/login': {
            componentId: "login"
        },

        '/signup': {
            componentId: "signup"
        },

        options: {
            hashbang: true,
            debug: true
        }
    }
~~~

I expect the login route to trigger and render the login component when the link is clicked but nothing happens. If the page is refreshed, the login route triggers.

I'm on latest Chrome.

**Comment by mgutz** [comment]
So the markup need to look like this regardless of the hashbang option

~~~html
<li><a href="/login">Log In</a></li>
~~~

And if you want to bypass routing, use `target="_self"`

~~~html
<li><a href="/realpage" target="_self">Log In</a></li>
~~~

**Comment by ayamflow** [comment]
Yes, links are independent from the hashbang. I will add this in the docs.
