### ISSUE TITLE
update $routeParams on cached keep-alive components?

### ISSUE THREAD

**Issue by inear** [ayamflow/vue-route#18]
I'm not sure about the best way to get the route param in the case where the component is cached. Right now it's overridden when the component is created, but if I navigate to a different view and then return with different parameters they are not updated (https://github.com/ayamflow/vue-route/blob/master/src/overrides.js#L33)

Are there better ways to keep track on the updated param? cc @kewah

**Comment by ayamflow** [comment]
Oh ok so if I understand correctly, instead of just returning the cached instance I should also
```js
cached.$data.$routeParams = this.location.params;
return cached;
```

Is that right ?

**Comment by inear** [comment]
That was how I solved it temporarily, but I lack the insight of the architecture to know if its a robust design or if I think wrong about the flow.

**Comment by ayamflow** [comment]
I will check but I think it should work without problem, although I have never use `keep-alive` before.

**Comment by ayamflow** [comment]
It was a a bit more than that, should do the trick!

**Comment by inear** [comment]
Nice! Thanks for looking into it!
