### ISSUE TITLE
preload components flow

### ISSUE THREAD

**Issue by inear** [ayamflow/vue-route#19]
If I want to load and init stuff async before switching to the new route (display a loader before going to the next route), where should I stop the route until it's ready? Should I use wait-for on the route-components? Where to put the markup in that case when the component is created by the router? Like {wait:true} in vue-view. Or are there better approaches for this built into Vue?

**Comment by ayamflow** [comment]
I haven't dug too deep in this direction - I used `wait-for` to delay the whole `v-route` component to appear if the data was not loaded. Gotcha: `wait-for` doesn't remember the state so if you go back to this component it will wait again for the `wait-for` event.

It should work with route components as well by putting the `wait-for` inside its template such as Vue.component('the-component') -> `<div class="TheComponent" wait-for>...</div>`. I guess you'll have to manually trigger an event to create/show the preloader (in the router before/afterUpdate?).

Another solution would be to use the `beforeUpdate` middleware `next()` function as a callback for the preloader so the route is processed only after load. You can still access the route parameters in the middleware to fetch/create the loader manifest.

I haven't tested anything, that's just what I would try knowing the vue-route flow. Let me know if anything works (or not!).

**Comment by inear** [comment]
Thanks for your reply! I sorted the first part out, getting the wait-for to work, but only if I put it in the root. I just had to delay the readyEvent-emit to make sure the parent was listening (in the case where the async callback was instant as it was when I first tested it).

But I struggle with how to tap into the hooks when revisiting the component the second time when using keep-alive and wait-for together. Before I started to use wait-for, I tapped into "attached", but that suppose to fire after the switch has been complete and after the readyEvent is emitted. The first time around I have a bunch of possible entry-points like created, compiled or ready. It's no problem that I have to trigger the readyEvent each time, since it's different API-calls, but I'm not sure where to init this calls and emit the readyEvent the second time.

The reason I try to reuse the components with keep-alive is that I switch between two sections that both uses three.js and with a lot of geometry and objects that is reused when toggle between the scenes. I want to show the loader over the current view instead of switching to a empty one while parsing all the data and geometry. It's not much content around the 3d-scenes so I should probably choose a different approach, just toggling components on/off with v-on in the same section, but I want to learn how to solve it this way just to learn for other times where it makes more sense to have different sections.

**Comment by ayamflow** [comment]
I'm not sure I understand everything but you should be able to `$dispatch` the readyEvent from anywhere to let it bubble to the correct component.

Even with a `keep-alive` component I think the `attached` hook should work - it is called at each append to the DOM (`ready` is only called once so I guess you shouldn't rely too much on it with `keep-alive`).

Does that help you in any way?

**Comment by inear** [comment]
I use dispatch already since it's a child component that do the loading. 'attached' works, but only when the readyEvent is dispatched. I mean that is what's it for, attaching the component when it's ready and not before? Without wait-for it's attached properly. I'm just not sure about where the component will be told it's about to be attached again so I can start the loading process again. But maybe I should post this question in the vue-repo instead, since it's not really vue-route-related?

**Comment by ayamflow** [comment]
Ah I understand better now. Yes this is tricky, I guess you need to $emit on the root or via an external mediator for the detached component to understand and start loading. Or maybe in the `beforeUpdate`? That would make sense i.e "what do I need to to before showing this component". The loader needs to be outside of the component though.

**Comment by inear** [comment]
I have tried to `$emit` (or `$broadcast` actually since it's a nested child) but all the children get's the event, since I'm using keep-alive and they are still in the _children list. So I need a way of addressing the event. Either by broadcast from the correct child component. I'm not sure how to get the reference though. In afterUpdate I have the component id, but camelCase it and access vm._children[sectionId] don't feel right. Have tried to use `v-ref` to save a ref $root.$, but they become null when returning to a component with keep-alive. Need to investigate why, or find a better way to reference i child. 

An alternative could be to name the event with the component-id, but it does not feel solid.

Maybe using the mediator-mixin to send unique events for each situation and component is the simplest way right now.

Yes, the loader will be global.

**Comment by ayamflow** [comment]
Yes exactly, I use the Vue events system for events that "traverse" the components tree, and mediator for specific use-cases.

**Comment by inear** [comment]
Thanks for your time and input!
