### ISSUE TITLE
v-transition confusion?

### ISSUE THREAD

**Issue by crswll** [ayamflow/vue-route#24]
Should i be able to do v-route with v-transition? The docs say "Routing directive for Vue.js (v0.11), inspired by ng-view. Based on v-component thus benefits from v-transition, keep-alive, wait-for, transition-mode." but I'm not sure I'm following right.

**Comment by ayamflow** [comment]
Basically, the `v-route` works as a `v-component` directive, so you can use the same options. This means than if you declare your container like `<div v-route v-transition="fade"></div>`, the `fade` transition will be called every time the route changes.

However, I usually recommend to use these options on your different "section" components so you can be much more specific. Something like...

```html
<!-- router element -->
<div v-route></div>

<!-- the home page, shown on / route -->
<div class="Home" keep-alive v-transition="homeTransition"></div>

<!-- the about page, shown on /about route -->
<div class="About" v-transition="aboutTransition"></div>
```

This way each component can define its own attribute. The home component will also be kept alive.

**Comment by crswll** [comment]
Ah, strange.

I can't get the transition to work if I put it on the v-route element itself:

    <div v-route class="fade" v-transition="fade" transition-mode="out-in"></div>

 but it does work if I put it on the individual views (with `replace: true` on `home` and `about`):

    <div v-route transition-mode="out-in"></div>
    <div class="home fade" v-transition="fade">
    <div class="about fade" v-transition="fade">

**Comment by ayamflow** [comment]
Can you make a fiddle?
Where are you declaring the transition?

**Comment by crswll** [comment]
I'm not sure how to use `vue-route` in a fiddle properly. Here's what I have though: http://jsbin.com/mufiqe/1/edit?js,output

**Comment by ayamflow** [comment]
I think I made a mistake; putting directives on the `v-route` tag will only be triggered if you change this element (with a v-if for instance), the opposite actually doesn't make sense.
I will update the documentation. Thanks for pointing this out!

**Comment by crswll** [comment]
Awesome. Thanks for clearing that up.
