### ISSUE TITLE
Error: Uncaught TypeError: Cannot read property 'bind' of undefined (Vue 0.12.0)

### ISSUE THREAD

**Issue by crswll** [ayamflow/vue-route#25]
The line it's pointing to is https://github.com/ayamflow/vue-route/blob/master/src/overrides.js#L18 I *think* line 10 needs to use `Vue.directive('_component')` instead of `Vue.directive('component')` solely based on this line of code from `vue-router` https://github.com/vuejs/vue-router/blob/master/src/view.js#L10.

 I gave it a shot but then I got another error: `this.update is not a function` on this line: https://github.com/ayamflow/vue-route/blob/master/src/routing.js#L147 so I'm not sure how component has changed to cause that error? The BEEFY tests are failing at 6.

**Comment by ayamflow** [comment]
Which version of Vue are you using?
Everything works as expected here, tests included, with 0.11.3.

If you're on 0.12, it's probably not backward-compatible thus the issues.
I guess I'll have to make it work soon with 0.12.

**Comment by crswll** [comment]
Yea it's 0.12, I mentioned it in the title. Just wanted to share what I've discovered so far about it.

**Comment by ayamflow** [comment]
Oh right, didn't pay attention. Thanks for the heads up! I'll investigate this when I have some time.

**Comment by swannknani** [comment]
+1 ;)

**Comment by rpkilby** [comment]
+1

**Comment by ayamflow** [comment]
Updated some stuff. Tests are passing now, let me know how it goes!
