### ISSUE TITLE
How would you pass params to component / view from route?

### ISSUE THREAD

**Issue by mrgodhani** [ayamflow/vue-route#27]
Hi,

I really like the plugin. But it would nice to show passing route params using code example in documentation. How do we pass params from route to view or component?

**Comment by ayamflow** [comment]
Let's use the main example from the README:
```
 '/items/:item': {
        componentId: 'fg-item',
        afterUpdate: 'updateHeader',
        data: {
            defaultColor: '#3453DD'
        }
    }
```

#### route params:
With location = `/item/someItem`:
```
ready: function() {
    console.log(this.$data.routeParams.item); // 'someItem'
}
```

#### passing data:
```
ready: function() {
    console.log(this.$data.defaultColor); // '#3453DD'
}
```

So you have 2 different things here: getting the route parameters or getting the custom data.
